# Header
menu:
  主页: /
  归档: /archives

# Content
excerpt_link: More
prev: Prev
next: Next
reply: Reply
fancybox: true

# Sidebar
widgets:
- music
- category
- recent_posts
- tag
- tagcloud

# Miscellaneous
google_analytics:
duoshuo_shortname: 
rss: 
google_site_verification: 
baidu_site_verification: 
favicon: 
music: 